spring.application.name=cashier-app
spring.jpa.open-in-view=false

spring.datasource.url=jdbc:h2:file:./data/cashier;DB_CLOSE_ON_EXIT=FALSE
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=sa
spring.datasource.password=

# dev only - off in Phase 6
spring.h2.console.enabled=true