package com.nexo.cashier.model;

public enum AuditEventType {
	APP_STARTED,
	APP_STOPPED,
	DAY_OPENED,
	SALE_COMPLETED,
	SALE_FAILED,
	LINE_VOIDED,
	CART_CLEARED,
	PRICE_OVERRIDE,
	STOCK_ADJUSTED,
	PRODUCTS_IMPORTED,
	BACKUP_CREATED,
	DAY_CLOSED
}